---
services:
  planos:
    image: guilhermenl/planos:latest 
    container_name: planos 
    environment:
      - DATABASE_URL=jdbc:postgresql://nimbus-db-dev.c1qqeeoy8ta4.us-east-1.rds.amazonaws.com:5432/nimbus_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=senha123
      - SERVER_PORT=8082
    ports:
      - 8082:8082

    networks:
      - nimbus_network
networks:
  nimbus_network:
