# The secret file contains the username and pasword for the database
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # Username must be encoded with base64 (echo -n 'decoded-text' | base64)
  username: <username>
  password: <password>
