---
services:
  enderecos:
    image: guilhermenl/enderecos:latest 
    container_name: enderecos
    environment:
      - DATABASE_URL=jdbc:postgresql://nimbus-db-dev.c1qqeeoy8ta4.us-east-1.rds.amazonaws.com:5432/nimbus_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=senha123
      - SERVER_PORT=8081
    ports:
      - 8081:8081

    networks:
      - nimbus_network
networks:
  nimbus_network:
    external: true
      