---
services:
  redis_api:
    image: guilhermenl/redis_api:latest 
    container_name: redis_api 
    environment:
      - DATABASE_URL=<URL>
      - DATABASE_USER=<USER>
      - DATABASE_PASSWORD=<PASSWORD>
      - SERVER_PORT=8080
    ports:
      - 8080:8080
